services:
  bot:
    build: .
    container_name: bot-colosseum
    restart: unless-stopped
    env_file:
      - .env
    command: ["python", "-m", "app.main", "run"]
    ports:
      - "8000:8000"

  migrate:
    build: .
    container_name: bot-colosseum-migrate
    env_file:
      - .env
    command: ["python", "-m", "app.main", "init-db"]
    profiles: ["tools"]
